"use client";
import { Box, Typography, useTheme } from "@mui/material";
import axios from "axios";
import Head from "next/head";
import React, { ReactNode } from "react";

import { useSettings } from "@/hooks/useSettings";
import LayoutNotApp from "@/views/layouts/LayoutNotApp";

export default function Home() {
  const theme = useTheme();
  const { settings } = useSettings();
  return (
    <>
      <Head>
        <title>Frontend Shop dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>;
Home.guestGuard = false;
Home.authGuard = false;