"use client";
import { Box, Typography, useTheme } from "@mui/material";
import axios from "axios";
import Head from "next/head";

import { useSettings } from "@/hooks/useSettings";
import CustomTextField from "@/components/text-field";

export default function Home() {
  const theme = useTheme();
  const { settings } = useSettings();
  console.log("theme", { theme, settings });
  return (
    <>
      <Head>
        <title>Frontend Shop dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
