import { NextPage } from "next";
import Head from "next/head";

type TProps = {

}
const Login: NextPage<TProps> = () => {

  return (
    <>
      <Head>
        <title>Frontend Shop dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
export default Login;
